### ISSUE TITLE
keepImport as ES import

### ISSUE THREAD

**Issue by stropho** [sormy/rollup-plugin-smart-asset#1]
First of all, thanks for the great plugin. It does what I need with the combination
```
url: 'copy',
keepImport: true,
```

I'm creating an esm bundle, and I'd like to keep ES imports, e.g.
```
import cssModule from './path/to/asset'
```
instead of the current `var cssModule = require('./path/to/asset')` in order to support proper tree-shaking in another/next bundler like webpack. 

Is it something that could be considered? I'm willing to do a PR - once we agree what would the new option be.

**Comment by sormy** [comment]
Last time I tried `import` approach I experienced issues because rollup tried to process import again and using `require` instead helped to solve the issue. 

If `import` will be used by default then rollup will bundle it as `require` or `import` depending on `output.format` value so we don't even need an option I guess. 

Feel free to submit a PR if you will find a way to render it as `import`.

**Comment by stropho** [comment]
It turns out out there is not a straight forward way solve it. Just the hacky ways :-D
Anyway, thanks for the quick reply.
