### ISSUE TITLE
Plugin requires Python and C++ Build Environment to set up

### ISSUE THREAD

**Issue by zhaparoff** [sormy/rollup-plugin-smart-asset#2]
This tool depends on _asset-hash_ package, which in its turn depends on _metrohash_, which requires Python and C++ compiler to be installed. 
Modern C++ build toolchain for Windows requires over 5 GB for setup. And it should be set up on any machine which will be used for builds.

Thus, I'm curious, if there is an option to use another hashing library instead, which wont't require a whole bunch of build tools for its installation?

**Comment by sormy** [comment]
`asset-hash` has support for standard hashes provided by node.js, `xxhash` (as optional dependency, if installed), and `metrohash` as mandatory dependency. I agree with raised concern but I think it could be wiser to make `metrohash` optional on `asset-hash` level rather than `rollup-plugin-smart-asset` level. I previously submitted PR to their repo to make `xxhash` optional and they accepted it. Could you please cut a ticket to `asset-hash` maintainers? If there will be resistance from their side then I can take a look on effort to remove `asset-hash` as dependency.

**Comment by zhaparoff** [comment]
Thank you for reply. I've created sebastian-software/asset-hash#3.

**Comment by transitive-bullshit** [comment]
@zhaparoff see my PR #4 for a workaround in the meantime.

**Comment by sormy** [comment]
Please test `2.0.0`. It is now independent from `asset-hash`, `metrohash` and `xxhash`.

**Comment by sormy** [comment]
Please close the ticket if verified new version and issue is resolved. Thank you.

**Comment by sormy** [comment]
Ping

**Comment by zhaparoff** [comment]
It worked for me. Thank you!
